version: "3.7"
services:
  app:
    container_name: aspcore
    hostname: aspcore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:443"
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - 2222:1433
    volumes:
      - ./sqldata:/var/opt/sql-server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: root1234!!
